# Generated by Django 2.1 on 2018-08-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
